### ISSUE TITLE
atx gui 蓝屏 

### ISSUE THREAD

**Issue by lyt19871224** [NetEaseGame/ATX#130]
python -m atx gui --serial http://localhost:5000  蓝屏

macOS 10.12.5
iphone 10.3.1
webdriveragent5.12日的源码  

![1 pic](https://cloud.githubusercontent.com/assets/7929135/26517326/082d0f58-42c9-11e7-82a1-e992e434c0a4.jpg)

**Comment by codeskyblue** [comment]
估计随着WDA的更新这个也自己好了，issue已经无法用来追查问题，关掉了
