### ISSUE TITLE
打开程序后无法swipe功能失效

### ISSUE THREAD

**Issue by nujhong** [NetEaseGame/ATX#133]
设备：安卓
测试对象：石器时代起源

对照过原生ui操作 `d.swipe(sx, sy, ex, ey)` 指令无效
后来发现将`d.start(package_name, ...)`去掉就可以了
怎样才能确保打开程序后仍然能使用swipe或者drag?

**Comment by codeskyblue** [comment]
start_app 只是调用了 adb shell am start -n 这个命令，理论上不应该影响的呀

**Comment by codeskyblue** [comment]
缺少再次反馈，暂时关闭
