### ISSUE TITLE
微信对话框闪退

### ISSUE THREAD

**Issue by Songyima** [NetEaseGame/ATX#148]
## Version information
- ATX Version: You can get from `python -matx version`
1.1.3.dev35
- Python Version: You can get from `python -V`
Python 2.7.10
## What steps will reproduce the problem?
点击微信对话框，每次点击都会闪退，新人求助……
## What is the expected output?
点击对话框之后应该是能进去对话界面的
## What do you see instead?
进去界面2s之后闪退
## Do you have any log or screenshots?
NO

移动互联网作业，我快疯了，网易dalao让我们测试抢红包……

**Comment by codeskyblue** [comment]
微信bug？

**Comment by Songyima** [comment]
也不一定是微信，感觉和系统也有关系吧，闪退的是iOS9.3.5，同一个版本微信，iOS10下没有闪退。解决办法可能就是升级系统了……

**Comment by codeskyblue** [comment]
你们的作业好有意思

**Comment by codeskyblue** [comment]
关掉了
