### ISSUE TITLE
WDA在Xcode9编译不通过

### ISSUE THREAD

**Issue by dropperY** [NetEaseGame/ATX#151]
## Version information
- ATX Version:  `1.1.3.dev36`
- Python Version:  `Python 2.7.12`

##WDA编译不通过

在Xcode9上这个wda的分支`a8def24ca67f8a74dd709b899c8ea539c9c488ea`无法编译通过，报
```
Implicit conversion from nullable pointer 'XCElementSnapshot * _Nullable' to non-nullable pointer type 'ObjectType _Nonnull' (aka 'id')
```

以及

```
'new' is unavailable: Use XCUIElementQuery to create XCUIElement instances.
```

是不是目前不支持Xcode9,iOS11

**Comment by codeskyblue** [comment]
换成最新版的wda试试，原理那个分支是适配xcode8的

**Comment by aixiaofeifei** [comment]
我用最新WDA的也可以  切换的这个分支就报一样的错  解决了么
