### ISSUE TITLE
d=atx.connect() #会报错提示：Function ‘connect’ does not return anythin

### ISSUE THREAD

**Issue by zhuhaoHappig** [NetEaseGame/ATX#155]
## Version information
- ATX Version: 1.1.3.dev36
- Python Version: python 27
- Windows环境，安卓测试

## What steps will reproduce the problem?

import atx
1、d=atx.connect() #这行会报错提示：Function ‘connect’ does not return anything如图1
2、且d. 后面跟不出任何方法，如图2
3、打印print(d)之后，控制台打印出：<atx.drivers.android.AndroidDevice object at 0x00000198F6CE8208>
4、强行运行d.screenshot("123.png")之后仍然报错
总结：
python正常环境和虚拟环境都试了，所以环境都安装成功，但都有此问题，求问什么原因？多谢了·

**Comment by codeskyblue** [comment]
这个是atx这个库设计的问题，太难fix了，只能从头写起。先放弃了
