### ISSUE TITLE
运行weditor，连接上手机后，点击reload报错

### ISSUE THREAD

**Issue by bsshanghai** [NetEaseGame/ATX#159]
D:\Python27-64bit\Scripts>python -m weditor
listen port 17310
[I 180118 15:23:16 web:2063] 304 GET /api/v1/version (::1) 0.00ms
[W 180118 15:23:24 web:2063] 430 POST /api/v1/connect (::1) 2107.00ms
[I 180118 15:23:44 web:2063] 200 POST /api/v1/connect (::1) 10124.00ms
SN a9e75fff-15fe-4350-8726-33c204cf524c
Traceback (most recent call last):
  File "D:\Python27-64bit\lib\site-packages\weditor\__main__.py", line 134, in g
et
    d.screenshot().convert("RGB").save(buffer, format='JPEG')
  File "D:\Python27-64bit\lib\site-packages\uiautomator2\__init__.py", line 756,
 in screenshot
    return Image.open(buff)
  File "D:\Python27-64bit\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
IOError: cannot identify image file <_io.BytesIO object at 0x00000000066F50F8>
[W 180118 15:23:55 web:2063] 430 GET /api/v1/devices/a9e75fff-15fe-4350-8726-33c
204cf524c/screenshot (::1) 126.00ms
**IOError: cannot identify image file**
这个错误说路径对应的文件不是有效的图片，网上搜的都说是PIL那边的问题，但是暂时还是不知道咋改.试了一两种imprt的方法，木有管用。so 先来问问.

**Comment by codeskyblue** [comment]
先直接写个脚本，看看`d.screenshot().save("some.png")`输出啥

**Comment by bsshanghai** [comment]
![image](https://user-images.githubusercontent.com/28524371/35130277-07be8e88-fcfb-11e7-8130-0afd5b606bee.png)


单纯截图，这句没有报错，图也保存成功。之前也一直有用这句截图。

**Comment by codeskyblue** [comment]
以修复
