### ISSUE TITLE
生成HTML報表時報錯

### ISSUE THREAD

**Issue by tobasi21** [NetEaseGame/ATX#163]
## Version information
- ATX Version: 1.2.1
- Python Version: 3.5

生成報告時，出現下列問題
只接單個裝置
![image](https://user-images.githubusercontent.com/24288844/35666754-24e97368-0766-11e8-904d-194e3f1fb99c.png)

因為完全參照GITHUB上面的方式安裝設定，可否協助查看是否哪裡有遺漏的嗎？
![image](https://user-images.githubusercontent.com/24288844/35666857-99e78222-0766-11e8-9146-db1241f1eb92.png)

**Comment by codeskyblue** [comment]
前几天更新了下代码，估计改坏了

**Comment by codeskyblue** [comment]
ref: https://github.com/NetEaseGame/ATX/issues/174
