### ISSUE TITLE
如何获取页面toast

### ISSUE THREAD

**Issue by BensonMax** [NetEaseGame/ATX#173]
如何获取页面toast ，在WEditor中无法获取
![_20180303222318](https://user-images.githubusercontent.com/31434954/36935451-e4b7f348-1f32-11e8-9270-78460ac41a51.png)

**Comment by BensonMax** [comment]
如何获取页面toast ，在WEditor中无法获取

**Comment by codeskyblue** [comment]
还不支持

**Comment by codeskyblue** [comment]
issue转移到 https://github.com/openatx/uiautomator2/issues/16
