### ISSUE TITLE
导入atx包后，里面的类的方法为什么不会支持联想呢？

### ISSUE THREAD

**Issue by rrandoom** [NetEaseGame/ATX#176]
使用的是pycharm，python 3.6  

code:
import atx 

d=atx.conncet()

'''
以下的cilck,screenshot等，在输入时无法自动补全，要一个一个去敲，能运行，但是会提示一个警告：sys:1: ResourceWarning: unclosed <socket.socket fd=724, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 6669), raddr=('127.0.0.1', 1040)>
'''
d.click("a.png")
d.screenshot('b.png')

**Comment by codeskyblue** [comment]
设计问题
