### ISSUE TITLE
atx.connect(host="192.168.118.130") not working

### ISSUE THREAD

**Issue by ghost** [NetEaseGame/ATX#177]
I'm working with  android x86 (http://www.android-x86.org/) and No serial number on emulator
code: 
device = atx.connect(host="192.168.118.130")
Following by:
https://stackoverflow.com/questions/10648009/debugging-using-a-virtual-machine-like-vmware-virtualbox/14811151
+Step 1: adb connect 192.168.1.51
+Step 2 adb devices
+step ...
Log error:
```
C:\python32\python-2.7.10\python.exe D:/source/abc/test.py
path: D:\source\abc
Traceback (most recent call last):
  File "D:/source/abc/test.py", line 7, in <module>
    u = device.connect(host="192.168.118.130")
  File "D:\source\abc\atx\__init__.py", line 72, in connect
    c = cls(*args, **kwargs)
  File "D:\source\abc\atx\drivers\android.py", line 86, in __init__
    self._adb_device = self._adb_client.device(serialno)
  File "D:\source\abc\atx\adbkit\client.py", line 110, in device
    raise EnvironmentError("Device not attached.")
EnvironmentError: Device not attached.

Process finished with exit code 1 
```

**Comment by codeskyblue** [comment]
If there is only one device, try call connect with out args

**Comment by codeskyblue** [comment]
Reopen it if you have more questions

**Comment by codeskyblue** [comment]
Just call with command `atx.connect()`
