### ISSUE TITLE
ios 屏幕旋转 测试横屏app出现点击位置不对

### ISSUE THREAD

**Issue by hao3tian6** [NetEaseGame/ATX#178]
## Version information
- ATX Version: You can get from `python -matx version`
ATX Version:1.2.1.dev3

- Python Version: You can get from `python -V`
Python 2.7.13

## What steps will reproduce the problem?
ios  home键在右方,测试横屏app 出现点击位置不对

=======================
试了设置 d.rotation = 1
会出现
AttributeError: can't set attribute  这个问题提示

d.rotation = None # default auto detect, 这个配置一下比较好，自动识别有时候识别不出来
# 0: home key bottom(normal)
# 1: home key right
# 2: home key top
# 3: home key left

**Comment by codeskyblue** [comment]
抱歉这么晚回复，设置rotation的接口，因为关闭了，所以这样。
这个问题的深度原因可能还是WebDriverAgent的问题，试试升级一下是不是可以解决。

**Comment by hao3tian6** [comment]
谢谢你的回答 ,我试一试

**Comment by codeskyblue** [comment]
还有问题，在WDA上看看issues吧，这里提问基本也没有好的解决办法
