### ISSUE TITLE
截图黑屏

### ISSUE THREAD

**Issue by wby238** [NetEaseGame/ATX#188]
## Version information
- ATX Version: 1.2.0
- Python Version: 3.6.2
- Memu模拟器

## What steps will reproduce the problem?
使用截图功能（`screen()`）的话得到的是一张全黑的图片。

**Comment by erbozhao** [comment]
模拟器截图黑屏啊~

**Comment by codeskyblue** [comment]
执行 ```adb shell rm /data/local/tmp/minicap```， 然后重试下
